# Generated by Django 4.2.5 on 2023-09-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avathar',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
